import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Ban, Check, Factory, FileSearch, ShieldCheck } from "lucide-react";
import { Navigation } from "@/app/components/Navigation";
import { Footer } from "@/app/components/sections/Footer";
import { SITE_URL } from "@/lib/site";

export const metadata: Metadata = {
  title: "Industrial AI Strategy: Systems Integrator Briefing",
  description: "An anonymised strategic briefing on how an established industrial systems integrator could use AI to reuse engineering knowledge, improve workflows and govern risk.",
  alternates: { canonical: `${SITE_URL}/briefings/industrial-ai-systems-integrator` },
  openGraph: { title: "Industrial AI Strategy: Systems Integrator Briefing", description: "A practical, anonymised research sample for established industrial and engineering businesses.", url: `${SITE_URL}/briefings/industrial-ai-systems-integrator`, type: "article" },
};

const EXPOSURE = [
  ["Requirements transcription", "Medium", "AI can structure a first pass; experienced engineers resolve ambiguity."],
  ["Routine code and configuration", "High", "Generation may accelerate; deterministic review and testing remain essential."],
  ["Documentation and validation", "Very high", "Strong potential for traceable drafts from approved project evidence."],
  ["Panel, field and site work", "Low", "Physical execution, safety ownership and site judgement remain human."],
  ["Support and incident triage", "Medium to high", "Historic cases can improve response preparation under engineer control."],
] as const;

export default function BriefingPage() {
  return <main className="min-h-screen bg-ivory text-ink"><Navigation />
    <section className="relative overflow-hidden bg-strath-navy pb-20 pt-36 text-white md:pb-28 md:pt-44"><div className="editorial-grid absolute inset-0 opacity-55" aria-hidden="true"/><div className="section-shell relative"><Link href="/#briefing" className="text-xs font-bold uppercase tracking-[0.16em] text-gold">← Return to AI advisory</Link><div className="mt-12 grid gap-12 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-8"><p className="section-kicker">Anonymised strategic research sample</p><h1 className="mt-7 text-[clamp(3rem,7vw,6.2rem)] font-semibold leading-[0.96] tracking-[-0.04em]">How agentic AI could reshape a 30-year-old industrial systems integrator.</h1><p className="mt-8 max-w-3xl text-xl leading-9 text-slate-300">How an established engineering business could convert project history and specialist knowledge into a durable operating advantage while retaining human technical authority.</p></div><div className="border border-gold/35 bg-gold/10 p-7 lg:col-span-4"><p className="text-xs font-bold uppercase tracking-[0.16em] text-gold">Important context</p><p className="mt-4 text-sm leading-7 text-slate-300">This is an anonymised strategic research sample based on public information. It is not an implementation case study, client result, functional safety audit or forecast.</p></div></div></div></section>
    <article>
      <section className="py-20 md:py-28"><div className="section-shell grid gap-12 lg:grid-cols-12"><aside className="lg:col-span-4"><p className="section-kicker !text-[#74521f]">Executive conclusion</p><div className="mt-7 border border-ink/15 bg-white p-7 shadow-[0_20px_60px_rgba(11,22,36,0.07)]"><Factory className="text-[#74521f]"/><p className="mt-5 text-lg font-semibold leading-8">The strategic goal is not to become an “AI company”. It is to become a stronger engineering company with AI embedded in controlled, reviewable work.</p></div></aside><div className="lg:col-span-8"><h2 className="text-4xl font-semibold leading-tight md:text-6xl">The competitive change is operational, not cosmetic.</h2><p className="mt-7 text-xl leading-9 text-slate-700">The likely threat is not a chatbot replacing an integrator. It is an AI-enabled competitor that can prepare quotations faster, reuse prior engineering decisions, produce routine documentation consistently and learn from every completed project.</p><p className="mt-6 text-lg leading-9 text-slate-600">The durable advantage remains the difficult human work: process interpretation, site reality, hazard and safety ownership, commissioning, accountability and customer trust. The opportunity is to give those people better leverage without pretending software owns their judgement.</p></div></div></section>
      <section className="bg-strath-navy py-20 text-white md:py-28"><div className="section-shell"><p className="section-kicker">Workflow exposure</p><h2 className="mt-6 max-w-4xl text-4xl font-semibold md:text-6xl">Where the operating model may change first.</h2><div className="mt-12 overflow-x-auto border border-white/10"><table className="w-full min-w-[760px] border-collapse text-left"><thead className="bg-gold text-ink"><tr><th className="p-5 text-xs uppercase tracking-[0.14em]">Workflow</th><th className="p-5 text-xs uppercase tracking-[0.14em]">Exposure</th><th className="p-5 text-xs uppercase tracking-[0.14em]">Practical interpretation</th></tr></thead><tbody>{EXPOSURE.map(row=><tr key={row[0]} className="border-t border-white/10"><th className="p-5 font-semibold text-white">{row[0]}</th><td className="p-5 text-gold">{row[1]}</td><td className="p-5 text-sm leading-7 text-slate-300">{row[2]}</td></tr>)}</tbody></table></div></div></section>
      <section className="py-20 md:py-28"><div className="section-shell"><div className="grid gap-8 lg:grid-cols-12"><div className="lg:col-span-7"><p className="section-kicker !text-[#74521f]">A practical 90-day pilot</p><h2 className="mt-6 text-4xl font-semibold md:text-6xl">Prove value on completed, non-safety-critical work.</h2></div><p className="text-lg leading-8 text-slate-600 lg:col-span-5 lg:pt-10">A useful pilot is bounded, measurable and deliberately unglamorous. It compares a shadow workflow with the original and produces a deploy, revise or stop decision.</p></div><div className="mt-12 grid gap-px border border-ink/15 bg-ink/15 lg:grid-cols-4">{[["Weeks 1–2","Set rules","Define data, access, review gates and prohibited actions."],["Weeks 3–4","Prepare a project","Choose a completed project and remove unauthorised data."],["Weeks 5–8","Run in shadow","Generate reviewable outputs with no connection to live systems."],["Weeks 9–12","Measure and decide","Compare time, defects, traceability, security and acceptance."]].map((step,index)=><div key={step[0]} className="bg-white p-7"><span className="font-mono text-xs text-[#74521f]">0{index+1} / {step[0]}</span><h3 className="mt-5 text-2xl font-semibold">{step[1]}</h3><p className="mt-4 text-sm leading-7 text-slate-600">{step[2]}</p></div>)}</div></div></section>
      <section className="bg-[#e9dfcf] py-20 md:py-28"><div className="section-shell grid gap-10 lg:grid-cols-2"><div className="border border-ink/15 bg-white p-8 md:p-10"><div className="flex items-center gap-4"><Check className="text-emerald-700"/><h2 className="text-3xl font-semibold">Good first use cases</h2></div><ul className="mt-7 space-y-4 text-base leading-7 text-slate-700">{["Explain and document a historic project", "Create a first-pass specification from approved source material", "Generate test cases for qualified engineer review", "Build a support knowledge base from resolved incidents"].map(item=><li key={item} className="flex gap-3"><Check size={16} className="mt-1 shrink-0 text-emerald-700"/>{item}</li>)}</ul></div><div className="border border-ink/15 bg-strath-navy p-8 text-white md:p-10"><div className="flex items-center gap-4"><Ban className="text-red-200"/><h2 className="text-3xl font-semibold">Poor first use cases</h2></div><ul className="mt-7 space-y-4 text-base leading-7 text-slate-300">{["Creating or modifying live safety logic", "Direct write access to production systems", "Bypassing normal review, simulation or testing", "Replacing engineering judgement before reliability is proven"].map(item=><li key={item} className="flex gap-3"><Ban size={16} className="mt-1 shrink-0 text-red-200"/>{item}</li>)}</ul></div></div></section>
      <section className="py-20 md:py-28"><div className="section-shell grid gap-12 lg:grid-cols-12"><div className="lg:col-span-5"><ShieldCheck size={34} className="text-[#74521f]"/><h2 className="mt-7 text-4xl font-semibold md:text-5xl">The asset is governed knowledge, not a general chatbot.</h2></div><div className="lg:col-span-7"><p className="text-xl leading-9 text-slate-700">The most valuable system would be grounded in approved project data, engineering standards, reusable modules, test evidence and senior engineers’ knowledge.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{["Named owners and revision dates", "Source links for generated outputs", "Least-privilege access", "Logs, rollback and stop conditions", "Client permission and IP review", "Qualified final approval"].map(item=><div key={item} className="flex items-start gap-3 border border-ink/15 bg-white p-5"><FileSearch size={17} className="mt-1 shrink-0 text-[#74521f]"/><span className="font-semibold">{item}</span></div>)}</div></div></div></section>
    </article>
    <section className="bg-strath-navy py-16 text-white"><div className="section-shell flex flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-gold">Your business will have a different answer</p><h2 className="mt-3 text-3xl font-semibold md:text-4xl">Start with your own workflows and evidence.</h2></div><Link href="/#contact" className="inline-flex min-h-14 items-center gap-3 bg-gold px-7 text-sm font-bold uppercase tracking-[0.14em] text-ink">Request an opportunity review <ArrowRight size={16}/></Link></div></section>
    <Footer />
  </main>;
}
